# Generated by Django 4.2.4 on 2023-09-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0003_rename_image_teams_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Teamss',
        ),
    ]
