# Generated by Django 4.2.4 on 2023-09-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0004_rename_teams_teamss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teamss',
            new_name='Teams',
        ),
    ]
